# Generated by Django 2.2 on 2022-09-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Money amount')),
                ('status', models.CharField(choices=[('created', 'created'), ('requested', 'request is sent'), ('unsuccessful', 'unsuccessful'), ('successful', 'successful')], max_length=20, verbose_name='status')),
                ('type', models.CharField(choices=[('instant', 'instant'), ('receipt', 'payment upon receipt')], max_length=20, verbose_name='type')),
            ],
        ),
    ]
