# Generated by Django 2.2 on 2022-09-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('requested', 'request is sent'), ('unsuccessful', 'unsuccessful'), ('successful', 'successful')], default='created', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('instant', 'instant'), ('receipt', 'payment upon receipt')], default='instant', max_length=20, verbose_name='type'),
        ),
    ]
