# Generated by Django 2.2 on 2022-09-26 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220926_0832'),
        ('payments', '0002_auto_20220923_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='order'),
            preserve_default=False,
        ),
    ]
