# Generated by Django 2.2 on 2022-09-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_money', models.FloatField(verbose_name='total money')),
                ('status', models.CharField(choices=[('created', 'Created order'), ('completed', 'On the assemply'), ('transfer', 'On a way to customer'), ('delivered', 'On a way to customer'), ('user_canceled', 'Canceled by customer'), ('shop_canceled', 'Canceled by shop')], max_length=20, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('completed', models.DateTimeField(verbose_name='completion time')),
            ],
        ),
    ]
