# Generated by Django 2.2 on 2022-09-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completion time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'Created order'), ('completed', 'On the assemply'), ('transfer', 'On a way to customer'), ('delivered', 'On a way to customer'), ('user_canceled', 'Canceled by customer'), ('shop_canceled', 'Canceled by shop')], default='created', max_length=20, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_money',
            field=models.FloatField(blank=True, null=True, verbose_name='total money'),
        ),
    ]
