# Generated by Django 2.2 on 2022-09-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220923_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'Created order'), ('confirmed', 'Confirmed'), ('transfer', 'On a way to customer'), ('delivered', 'On a way to customer'), ('user_canceled', 'Canceled by customer'), ('shop_canceled', 'Canceled by shop')], default='created', max_length=20, null=True, verbose_name='status'),
        ),
    ]
